### ISSUE TITLE
[5/10] CI Phase 1 - Checkpoint 1

### ISSUE THREAD

**Issue by dcao** [cse110-sp21-group17/cse110-sp21-group17#31]
Per [Canvas](https://canvas.ucsd.edu/courses/25069/assignments/281339), the following should be implemented by this point:

- [x] linting and code style enforcement (look into https://editorconfig.org/ and set up enforcement in pipeline)
- [x] code quality via human review (ex. Pull Requests)

Additionally, the following should be looked into:
- [x] code quality via tool (ex. Codeclimate, Codacy, etc.)
- [x] unit tests via automation (ex. Jest, Tape, Ava, Cypress, Mocha/Chai, etc.)*
- [x] documentation generation via automation (ex. JSDocs)
- [ ] CLEAN UP THE REPO AND GET OUR GITHUB PAGES TO LINK THE CODE DOCUMENTATION

**Comment by JasonSatherr** [comment]
Completed.
